test:
  script:
    - echo "Running testing script"

build:docker:
  script:
    - echo "Running build docker image script"
    - exho "Running push docker image to registry script"

deploy:prod:
  script:
    - echo "Running deploy script"
